version: '3.1'

services:

  mysql:
    image: arm64v8/mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./mysql:/var/lib/mysql

  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./logs:/usr/share/nginx/html:ro
      - ./config/nginx-setup.mime.types:/etc/nginx/mime.types 


volumes:
  mysql:



