#! /bin/bash


unpack_files () {
	
	cd html &&\
	test -f "$1" &&\
	echo extracting $1 &&\
	sudo -u www-data unzip -o $1 >/dev/null &&\
	cd ..
}


install_db () {
     make cli CLI="db drop" &&\
     make cli CLI="db create" &&\
     make cli CLI='db import /var/www/'$(find html/dup-installer -name '*sql') &&\
     make set-cname
}


do_cleanup () {
     # Memcachey remove
     sudo rm html/wp-content/object-cache.php html/wp-content/object-cache-memcache.php html/wp-content/object-cache-memcached.php
     # dup-installer remove
     sudo rm -rf html/dup-installer html/installer.php html/installer-backup.php html/installer-bootlog.txt html/dpro-importinstaller.php html/dup-wp-config-arc__*.txt
     make cli CLI='plugin deactivate wp-ses'
     make cli CLI='plugin deactivate duplicator-pro'
}

make_visible () {
     make cli CLI='--skip-plugins option set blogname shop-test'
     export TMPFILE=/tmp/users.$$
     trap "{ rm $TMPFILE &2>/dev/null; }" EXIT 
     make cli CLI='user list --role=administrator --field=user_email' >>$TMPFILE
     make cli CLI='user list --role=shop_manager --field=user_email'  >>$TMPFILE
     for USER in $(cat $TMPFILE | tr -d '\15\32') ; do 
        make cli CLI='user meta update '$USER' admin_color sunrise'
     done
}     

help() {
cat <<__EOF__

$0 [absolute pathname of .zip archive]

... unpacks an archive generated by Duplicator Pro and installs it

__EOF__
}


if [ -f "$1" ]; then
	unpack_files $1
	install_db
	do_cleanup
	make_visible
else
	if [ "$1" == "" ] ; then
	    help
	else
	  for a in $*; do
		$a
	  done
        fi 
fi


