version: '3.3'



services:

  wordpress:
    image: wordpress:4.9-php7.1-apache
    ports:
      - "${WORDPRESS_PORT}:80"
      # - "80"
    environment:
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./html:/var/www/html
      - ./php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - wordpress

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - wordpress


networks:
    wordpress:
        attachable: true

# STACK_NAME := vmonitor

# MYSQL_ROOT_PASSWORD := 0fb7cef4b333b067c27558546088d03a
# WORDPRESS_PORT	    := 80 


