version: '3.3'



services:

  wordpress:
    image: wordpress:4.9-php7.1-apache
    ports:
      - "${WORDPRESS_PORT}:80"
      # - "80"
    environment:
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_NAME}
    volumes:
      - ./html:/var/www/html
      - ./php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - ${MYSQL_NETWORK}



