version: '3.1'

services:

  wordpress:
    image: wordpress:4.9-php7.1-apache
    restart: always
    ports:
      - ${WORDPRESS_PORT}:80
    environment:
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./html:/var/www/html
      - ./php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql




# STACK_NAME := vmonitor

# MYSQL_ROOT_PASSWORD := 0fb7cef4b333b067c27558546088d03a
# WORDPRESS_PORT	    := 80 


